const START_LOAD_DATABASE = "app/pokemon/START_LOAD_DATABASE";
const LOAD_DATABASE = "app/pokemon/LOAD_DATABASE";
const END_LOAD_DATABASE = "app/pokemon/END_LOAD_DATABASE";

export default {
    START_LOAD_DATABASE,
    LOAD_DATABASE,
    END_LOAD_DATABASE
};
